### ISSUE TITLE
Sorties avec les LED Bar

### ISSUE THREAD

**Issue by fabienarg** [lycee-chaptal-sii/fab-pierreg-ali-simon#1]
@atrantan Bonjour, je cherche à configurer les bonnes sorties pour les deux feux tricolores mais vu qu'on utilise les LED Bar je sais pas comment faire, pouvez-vous jeter un oeil au ficher main.ino sur la branche partie_pratique pour me suggérer des changements dans le code svp.

**Comment by atrantan** [comment]
@fabienarg Tu dois t'inspirer du code exemple utilisant les LED Bar ici: https://github.com/lycee-chaptal-sii/fab-pierreg-ali-simon/blob/exemple/main.ino
Pour faire simple,  tu dois créer une variable de type `Grove_LED_Bar` comme ici https://github.com/lycee-chaptal-sii/fab-pierreg-ali-simon/blob/b81c647036ffeec36e640cf70b65ff22bd5c300a/main.ino#L27
(le `7` et le `6` donné en paramètre du "constructeur" correspond aux Digital pins utilisés pour __une__ Grove_LED_Bar). Ensuite si tu veux allumer tel ou tel LED c'est ça, par exemple: https://github.com/lycee-chaptal-sii/fab-pierreg-ali-simon/blob/b81c647036ffeec36e640cf70b65ff22bd5c300a/main.ino#L47

**Comment by atrantan** [comment]
@fabienarg L'utilisation des `Grove_LED_Bar` semble être compris.
